spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: AUTH-SERVICE-SECURED
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/login/**

            - id: AUTH-SERVICE-OPEN
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/login
              filters:
                - RewritePath=/api/login, /api/login

            - id: EMPLOYEE-SERVICE-SECURED
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/employees/**,/api/teams/**
              filters:
                - JwtAuthenticationFilter

            - id: EMPLOYEE-SERVICE-OPEN
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/employees
              filters:
                - RewritePath=/api/employees, /api/employees

            - id: SHIFT-SERVICE-SECURED
              uri: lb://SHIFT-SERVICE
              predicates:
                - Path=/api/shifts/**,/api/shift-swap-requests/**
              filters:
                - JwtAuthenticationFilter


server:
  port: 8080

jwt:
  secret: ${secret_signing_key}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.hostname}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
