spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: AUTH-SERVICE-OPENAPI
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/v3/api-docs/auth-service
              filters:
                - RewritePath=/v3/api-docs/auth-service,/v3/api-docs

            - id: EMPLOYEE-SERVICE-OPENAPI
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/v3/api-docs/employee-service
              filters:
                - RewritePath=/v3/api-docs/employee-service,/v3/api-docs

            - id: ATTENDANCE-SERVICE-OPENAPI
              uri: lb://ATTENDANCE-SERVICE
              predicates:
                - Path=/v3/api-docs/attendance-service
              filters:
                - RewritePath=/v3/api-docs/attendance-service,/v3/api-docs

            - id: SHIFT-SERVICE-OPENAPI
              uri: lb://SHIFT-SERVICE
              predicates:
                - Path=/v3/api-docs/shift-service
              filters:
                - RewritePath=/v3/api-docs/shift-service,/v3/api-docs

            - id: LEAVE-SERVICE-OPENAPI
              uri: lb://LEAVE-SERVICE
              predicates:
                - Path=/v3/api-docs/leave-service
              filters:
                - RewritePath=/v3/api-docs/leave-service,/v3/api-docs

            - id: REPORT-SERVICE-OPENAPI
              uri: lb://REPORT-SERVICE
              predicates:
                - Path=/v3/api-docs/report-service
              filters:
                - RewritePath=/v3/api-docs/report-service,/v3/api-docs

            - id: AUTH-SERVICE-SECURED
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/login/**

            - id: AUTH-SERVICE-OPEN
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/login
              filters:
                - RewritePath=/api/login, /api/login

            - id: EMPLOYEE-SERVICE-SECURED
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/employees/**,/api/teams/**
              filters:
                - JwtAuthenticationFilter

            - id: EMPLOYEE-SERVICE-OPEN
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/employees
              filters:
                - RewritePath=/api/employees, /api/employees

            - id: SHIFT-SERVICE-SECURED
              uri: lb://SHIFT-SERVICE
              predicates:
                - Path=/api/shifts/**,/api/shift-swap-requests/**
              filters:
                - JwtAuthenticationFilter

            - id: LEAVE-SERVICE-SECURED
              uri: lb://LEAVE-SERVICE
              predicates:
                - Path=/api/leave-balances/**,/api/leave-requests/employees/**,/api/leave-requests/manager/**
              filters:
                - JwtAuthenticationFilter

            - id: ATTENDANCE-SERVICE-SECURED
              uri: lb://ATTENDANCE-SERVICE
              predicates:
                - Path=/api/attendances/**
              filters:
                - JwtAuthenticationFilter

            - id: REPORT-SERVICE-SECURED
              uri: lb://REPORT-SERVICE
              predicates:
                - Path=/api/reports/**
              filters:
                - JwtAuthenticationFilter

server:
  port: 8080

jwt:
  secret: ${secret_signing_key}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.hostname}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: employee-service
        url: /v3/api-docs/employee-service
      - name: shift-service
        url: /v3/api-docs/shift-service
      - name: attendance-service
        url: /v3/api-docs/attendance-service
      - name: leave-service
        url: /v3/api-docs/leave-service
      - name: report-service
        url: /v3/api-docs/report-service
    persist-authorization: true